"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a82e8818fb5
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClassifierFTModelOut$inboundSchema = void 0;
exports.classifierFTModelOutFromJSON = classifierFTModelOutFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const classifiertargetout_js_1 = require("./classifiertargetout.js");
const ftmodelcapabilitiesout_js_1 = require("./ftmodelcapabilitiesout.js");
/** @internal */
exports.ClassifierFTModelOut$inboundSchema = z.object({
    id: z.string(),
    object: z.literal("model").default("model"),
    created: z.number().int(),
    owned_by: z.string(),
    workspace_id: z.string(),
    root: z.string(),
    root_version: z.string(),
    archived: z.boolean(),
    name: z.nullable(z.string()).optional(),
    description: z.nullable(z.string()).optional(),
    capabilities: ftmodelcapabilitiesout_js_1.FTModelCapabilitiesOut$inboundSchema,
    max_context_length: z.number().int().default(32768),
    aliases: z.array(z.string()).optional(),
    job: z.string(),
    classifier_targets: z.array(classifiertargetout_js_1.ClassifierTargetOut$inboundSchema),
    model_type: z.literal("classifier").default("classifier"),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "owned_by": "ownedBy",
        "workspace_id": "workspaceId",
        "root_version": "rootVersion",
        "max_context_length": "maxContextLength",
        "classifier_targets": "classifierTargets",
        "model_type": "modelType",
    });
});
function classifierFTModelOutFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.ClassifierFTModelOut$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ClassifierFTModelOut' from JSON`);
}
//# sourceMappingURL=classifierftmodelout.js.map