"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 023005f82be7
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageInputEntry$outboundSchema = exports.MessageInputEntry$inboundSchema = exports.MessageInputEntryContent$outboundSchema = exports.MessageInputEntryContent$inboundSchema = exports.Role$outboundSchema = exports.Role$inboundSchema = exports.Role = void 0;
exports.messageInputEntryContentToJSON = messageInputEntryContentToJSON;
exports.messageInputEntryContentFromJSON = messageInputEntryContentFromJSON;
exports.messageInputEntryToJSON = messageInputEntryToJSON;
exports.messageInputEntryFromJSON = messageInputEntryFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const messageinputcontentchunks_js_1 = require("./messageinputcontentchunks.js");
exports.Role = {
    Assistant: "assistant",
    User: "user",
};
/** @internal */
exports.Role$inboundSchema = z.nativeEnum(exports.Role);
/** @internal */
exports.Role$outboundSchema = exports.Role$inboundSchema;
/** @internal */
exports.MessageInputEntryContent$inboundSchema = z.union([z.string(), z.array(messageinputcontentchunks_js_1.MessageInputContentChunks$inboundSchema)]);
/** @internal */
exports.MessageInputEntryContent$outboundSchema = z.union([z.string(), z.array(messageinputcontentchunks_js_1.MessageInputContentChunks$outboundSchema)]);
function messageInputEntryContentToJSON(messageInputEntryContent) {
    return JSON.stringify(exports.MessageInputEntryContent$outboundSchema.parse(messageInputEntryContent));
}
function messageInputEntryContentFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.MessageInputEntryContent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'MessageInputEntryContent' from JSON`);
}
/** @internal */
exports.MessageInputEntry$inboundSchema = z.object({
    object: z.literal("entry").default("entry"),
    type: z.literal("message.input").default("message.input"),
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
        .optional(),
    completed_at: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))).optional(),
    id: z.string().optional(),
    role: exports.Role$inboundSchema,
    content: z.union([
        z.string(),
        z.array(messageinputcontentchunks_js_1.MessageInputContentChunks$inboundSchema),
    ]),
    prefix: z.boolean().default(false),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "created_at": "createdAt",
        "completed_at": "completedAt",
    });
});
/** @internal */
exports.MessageInputEntry$outboundSchema = z.object({
    object: z.literal("entry").default("entry"),
    type: z.literal("message.input").default("message.input"),
    createdAt: z.date().transform(v => v.toISOString()).optional(),
    completedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
    id: z.string().optional(),
    role: exports.Role$outboundSchema,
    content: z.union([
        z.string(),
        z.array(messageinputcontentchunks_js_1.MessageInputContentChunks$outboundSchema),
    ]),
    prefix: z.boolean().default(false),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        createdAt: "created_at",
        completedAt: "completed_at",
    });
});
function messageInputEntryToJSON(messageInputEntry) {
    return JSON.stringify(exports.MessageInputEntry$outboundSchema.parse(messageInputEntry));
}
function messageInputEntryFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.MessageInputEntry$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'MessageInputEntry' from JSON`);
}
//# sourceMappingURL=messageinputentry.js.map