"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 49d94b5646c9
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatCompletionEventPreview$inboundSchema = exports.ExtraFields$inboundSchema = void 0;
exports.extraFieldsFromJSON = extraFieldsFromJSON;
exports.chatCompletionEventPreviewFromJSON = chatCompletionEventPreviewFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
/** @internal */
exports.ExtraFields$inboundSchema = z.union([
    z.boolean(),
    z.number().int(),
    z.number(),
    z.string(),
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
    z.array(z.string()),
]);
function extraFieldsFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.ExtraFields$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ExtraFields' from JSON`);
}
/** @internal */
exports.ChatCompletionEventPreview$inboundSchema = z.object({
    event_id: z.string(),
    correlation_id: z.string(),
    created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    extra_fields: z.record(z.nullable(z.union([
        z.boolean(),
        z.number().int(),
        z.number(),
        z.string(),
        z.string().datetime({ offset: true }).transform(v => new Date(v)),
        z.array(z.string()),
    ]))),
    nb_input_tokens: z.number().int(),
    nb_output_tokens: z.number().int(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "event_id": "eventId",
        "correlation_id": "correlationId",
        "created_at": "createdAt",
        "extra_fields": "extraFields",
        "nb_input_tokens": "nbInputTokens",
        "nb_output_tokens": "nbOutputTokens",
    });
});
function chatCompletionEventPreviewFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.ChatCompletionEventPreview$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatCompletionEventPreview' from JSON`);
}
//# sourceMappingURL=chatcompletioneventpreview.js.map