/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { ChatContentStartEventDeltaMessageContent } from "./ChatContentStartEventDeltaMessageContent";
export declare const ChatContentStartEventDeltaMessage: core.serialization.ObjectSchema<serializers.ChatContentStartEventDeltaMessage.Raw, Cohere.ChatContentStartEventDeltaMessage>;
export declare namespace ChatContentStartEventDeltaMessage {
    interface Raw {
        content?: ChatContentStartEventDeltaMessageContent.Raw | null;
    }
}
