operationId: getUser
tags:
  - User
summary: Get user by ID/Email
description: Retrieve a user from your instance. Only available for the instance owner.
x-required-scope: user:read
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    description: The ID or email of the user.
    name: userId
    in: path
  - schema:
      type: string
      enum:
        - 'true'
        - 'false'
      default: 'false'
    required: false
    name: includeRole
    in: query
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: string
              readOnly: true
              example: 123e4567-e89b-12d3-a456-426614174000
            email:
              type: string
              format: email
              example: john.doe@company.com
            firstName:
              type: string
              nullable: true
              readOnly: true
              example: john
            lastName:
              type: string
              nullable: true
              readOnly: true
              example: Doe
            isPending:
              type: boolean
              description: Whether the user finished setting up their account in response to the invitation (true) or not (false).
              readOnly: true
            createdAt:
              type: string
              format: date-time
              readOnly: true
            updatedAt:
              type: string
              format: date-time
              readOnly: true
            mfaEnabled:
              type: boolean
              description: Whether the user has multi-factor authentication (MFA/2FA) enabled.
              readOnly: true
              example: false
            role:
              type: string
              readOnly: true
              example: global:owner
          required:
            - id
            - email
            - firstName
            - lastName
            - isPending
            - createdAt
            - updatedAt
            - mfaEnabled
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    description: No user with that ID or email.
