/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { ClassifyResponseClassificationsItemLabelsValue } from "./ClassifyResponseClassificationsItemLabelsValue";
import { ClassifyResponseClassificationsItemClassificationType } from "./ClassifyResponseClassificationsItemClassificationType";
export declare const ClassifyResponseClassificationsItem: core.serialization.ObjectSchema<serializers.ClassifyResponseClassificationsItem.Raw, Cohere.ClassifyResponseClassificationsItem>;
export declare namespace ClassifyResponseClassificationsItem {
    interface Raw {
        id: string;
        input?: string | null;
        prediction?: string | null;
        predictions: string[];
        confidence?: number | null;
        confidences: number[];
        labels: Record<string, ClassifyResponseClassificationsItemLabelsValue.Raw>;
        classification_type: ClassifyResponseClassificationsItemClassificationType.Raw;
    }
}
