"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 06c32b85d8c1
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConversationHistory$inboundSchema = exports.Entries$inboundSchema = void 0;
exports.entriesFromJSON = entriesFromJSON;
exports.conversationHistoryFromJSON = conversationHistoryFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const agenthandoffentry_js_1 = require("./agenthandoffentry.js");
const functioncallentry_js_1 = require("./functioncallentry.js");
const functionresultentry_js_1 = require("./functionresultentry.js");
const messageinputentry_js_1 = require("./messageinputentry.js");
const messageoutputentry_js_1 = require("./messageoutputentry.js");
const toolexecutionentry_js_1 = require("./toolexecutionentry.js");
/** @internal */
exports.Entries$inboundSchema = z.union([
    agenthandoffentry_js_1.AgentHandoffEntry$inboundSchema,
    functioncallentry_js_1.FunctionCallEntry$inboundSchema,
    messageinputentry_js_1.MessageInputEntry$inboundSchema,
    functionresultentry_js_1.FunctionResultEntry$inboundSchema,
    toolexecutionentry_js_1.ToolExecutionEntry$inboundSchema,
    messageoutputentry_js_1.MessageOutputEntry$inboundSchema,
]);
function entriesFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.Entries$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Entries' from JSON`);
}
/** @internal */
exports.ConversationHistory$inboundSchema = z.object({
    object: z.literal("conversation.history").default("conversation.history"),
    conversation_id: z.string(),
    entries: z.array(z.union([
        agenthandoffentry_js_1.AgentHandoffEntry$inboundSchema,
        functioncallentry_js_1.FunctionCallEntry$inboundSchema,
        messageinputentry_js_1.MessageInputEntry$inboundSchema,
        functionresultentry_js_1.FunctionResultEntry$inboundSchema,
        toolexecutionentry_js_1.ToolExecutionEntry$inboundSchema,
        messageoutputentry_js_1.MessageOutputEntry$inboundSchema,
    ])),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "conversation_id": "conversationId",
    });
});
function conversationHistoryFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.ConversationHistory$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ConversationHistory' from JSON`);
}
//# sourceMappingURL=conversationhistory.js.map