/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-01
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SearchRecordsVector } from './SearchRecordsVector';
/**
 * The query inputs to search with. Each request can contain only one of the following parameters: `inputs`, `vector`, or `id`.
 * @export
 * @interface SearchRecordsRequestQuery
 */
export interface SearchRecordsRequestQuery {
    /**
     * The number of similar records to return.
     * @type {number}
     * @memberof SearchRecordsRequestQuery
     */
    topK: number;
    /**
     * The filter to apply. You can use vector metadata to limit your search. See [Understanding metadata](https://docs.pinecone.io/guides/data/understanding-metadata).
     * @type {object}
     * @memberof SearchRecordsRequestQuery
     */
    filter?: object;
    /**
     *
     * @type {object}
     * @memberof SearchRecordsRequestQuery
     */
    inputs?: object;
    /**
     *
     * @type {SearchRecordsVector}
     * @memberof SearchRecordsRequestQuery
     */
    vector?: SearchRecordsVector;
    /**
     * The unique ID of the vector to be used as a query vector.
     * @type {string}
     * @memberof SearchRecordsRequestQuery
     */
    id?: string;
}
/**
 * Check if a given object implements the SearchRecordsRequestQuery interface.
 */
export declare function instanceOfSearchRecordsRequestQuery(value: object): boolean;
export declare function SearchRecordsRequestQueryFromJSON(json: any): SearchRecordsRequestQuery;
export declare function SearchRecordsRequestQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRecordsRequestQuery;
export declare function SearchRecordsRequestQueryToJSON(value?: SearchRecordsRequestQuery | null): any;
