operationId: deleteGitConnection
tags:
  - GitConnections
summary: Delete a Git connection
description: Deletes a Git connection and its local files.
x-required-scope: gitConnection:delete
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    name: id
    in: path
responses:
  '204':
    description: Operation successful.
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
