/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Cohere from "../../../../../index";
/**
 * Response to a request to get a fine-tuned model.
 */
export interface GetFinetunedModelResponse {
    /** Information about the fine-tuned model. */
    finetunedModel?: Cohere.finetuning.FinetunedModel;
}
