operationId: listConnections
tags:
  - External Secrets
summary: List external secrets connections
description: Retrieve external secrets provider connections from your instance.
x-required-scope: externalSecretsProvider:list
parameters:
  - $ref: ../../../../shared/spec/parameters/limit.yml
  - $ref: ../../../../shared/spec/parameters/cursor.yml
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  type:
                    type: string
                    enum:
                      - awsSecretsManager
                      - gcpSecretsManager
                      - vault
                      - azureKeyVault
                      - infisical
                      - onePassword
                  state:
                    type: string
                    enum:
                      - initializing
                      - initialized
                      - connecting
                      - connected
                      - error
                      - retrying
                  isEnabled:
                    type: boolean
                  managedBy:
                    type: string
                    enum:
                      - api
                      - config-file
                  projects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        role:
                          type: string
                          enum:
                            - secretsProviderConnection:owner
                            - secretsProviderConnection:user
                      required:
                        - id
                        - name
                  secretsCount:
                    type: number
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                required:
                  - id
                  - name
                  - type
                  - state
                  - isEnabled
                  - managedBy
                  - projects
                  - secretsCount
                  - createdAt
                  - updatedAt
            nextCursor:
              type: string
              nullable: true
          required:
            - data
            - nextCursor
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
