"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentsApiV1ConversationsAppendStreamRequest$ = exports.AgentsApiV1ConversationsAppendStreamRequest$outboundSchema = exports.AgentsApiV1ConversationsAppendStreamRequest$inboundSchema = void 0;
exports.agentsApiV1ConversationsAppendStreamRequestToJSON = agentsApiV1ConversationsAppendStreamRequestToJSON;
exports.agentsApiV1ConversationsAppendStreamRequestFromJSON = agentsApiV1ConversationsAppendStreamRequestFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const components = __importStar(require("../components/index.js"));
/** @internal */
exports.AgentsApiV1ConversationsAppendStreamRequest$inboundSchema = z.object({
    conversation_id: z.string(),
    ConversationAppendStreamRequest: components.ConversationAppendStreamRequest$inboundSchema,
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "conversation_id": "conversationId",
        "ConversationAppendStreamRequest": "conversationAppendStreamRequest",
    });
});
/** @internal */
exports.AgentsApiV1ConversationsAppendStreamRequest$outboundSchema = z.object({
    conversationId: z.string(),
    conversationAppendStreamRequest: components.ConversationAppendStreamRequest$outboundSchema,
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        conversationId: "conversation_id",
        conversationAppendStreamRequest: "ConversationAppendStreamRequest",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var AgentsApiV1ConversationsAppendStreamRequest$;
(function (AgentsApiV1ConversationsAppendStreamRequest$) {
    /** @deprecated use `AgentsApiV1ConversationsAppendStreamRequest$inboundSchema` instead. */
    AgentsApiV1ConversationsAppendStreamRequest$.inboundSchema = exports.AgentsApiV1ConversationsAppendStreamRequest$inboundSchema;
    /** @deprecated use `AgentsApiV1ConversationsAppendStreamRequest$outboundSchema` instead. */
    AgentsApiV1ConversationsAppendStreamRequest$.outboundSchema = exports.AgentsApiV1ConversationsAppendStreamRequest$outboundSchema;
})(AgentsApiV1ConversationsAppendStreamRequest$ || (exports.AgentsApiV1ConversationsAppendStreamRequest$ = AgentsApiV1ConversationsAppendStreamRequest$ = {}));
function agentsApiV1ConversationsAppendStreamRequestToJSON(agentsApiV1ConversationsAppendStreamRequest) {
    return JSON.stringify(exports.AgentsApiV1ConversationsAppendStreamRequest$outboundSchema.parse(agentsApiV1ConversationsAppendStreamRequest));
}
function agentsApiV1ConversationsAppendStreamRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.AgentsApiV1ConversationsAppendStreamRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'AgentsApiV1ConversationsAppendStreamRequest' from JSON`);
}
//# sourceMappingURL=agentsapiv1conversationsappendstream.js.map