/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const ResponseFormats = {
  Text: "text",
  JsonObject: "json_object",
  JsonSchema: "json_schema",
} as const;
export type ResponseFormats = ClosedEnum<typeof ResponseFormats>;

/** @internal */
export const ResponseFormats$outboundSchema: z.ZodNativeEnum<
  typeof ResponseFormats
> = z.nativeEnum(ResponseFormats);
