/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-01
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * A record whose vector values are similar to the provided search query.
 * @export
 * @interface Hit
 */
export interface Hit {
    /**
     * The record id of the search hit.
     * @type {string}
     * @memberof Hit
     */
    _id: string;
    /**
     * The similarity score of the returned record.
     * @type {number}
     * @memberof Hit
     */
    _score: number;
    /**
     * The selected record fields associated with the search hit.
     * @type {object}
     * @memberof Hit
     */
    fields: object;
}
/**
 * Check if a given object implements the Hit interface.
 */
export declare function instanceOfHit(value: object): boolean;
export declare function HitFromJSON(json: any): Hit;
export declare function HitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hit;
export declare function HitToJSON(value?: Hit | null): any;
