type: object
properties:
  name:
    $ref: './dataTableColumnName.yml'
  index:
    type: integer
    minimum: 0
    description: New zero-based position for the column
additionalProperties: false
anyOf:
  - required: [name]
  - required: [index]
