/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         metadata: {}
 *     }
 */
export interface ModelsMessageMetadataUpdate {
    /** The metadata to update */
    metadata: Record<string, unknown>;
}
