"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmbedInputType = void 0;
exports.EmbedInputType = {
    SearchDocument: "search_document",
    SearchQuery: "search_query",
    Classification: "classification",
    Clustering: "clustering",
    Image: "image",
};
