/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Zep from "../../../../../api/index";
import * as core from "../../../../../core";
import { SearchScope } from "../../../../types/SearchScope";
import { SearchType } from "../../../../types/SearchType";
export declare const SessionSearchQuery: core.serialization.Schema<serializers.SessionSearchQuery.Raw, Omit<Zep.SessionSearchQuery, "limit">>;
export declare namespace SessionSearchQuery {
    interface Raw {
        min_score?: number | null;
        mmr_lambda?: number | null;
        record_filter?: Record<string, unknown> | null;
        search_scope?: SearchScope.Raw | null;
        search_type?: SearchType.Raw | null;
        session_ids?: string[] | null;
        text?: string | null;
        user_id?: string | null;
    }
}
