operationId: getDeprecatedWorkflowVersion
tags:
  - Workflow
summary: Retrieves a specific version of a workflow
description: 'Deprecated: use GET /workflows/{workflowId}/versions/{workflowVersionId} instead. Retrieves a specific version of a workflow from workflow history.'
x-required-scope: workflow:read
deprecated: true
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    description: The ID of the workflow.
    name: workflowId
    in: path
  - schema:
      type: string
    required: true
    description: The ID of the workflow version.
    name: workflowVersionId
    in: path
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          $ref: ../../../../shared/spec/schemas/workflowVersionPublicDto.generated.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
