operationId: updateWorkflowTags
tags:
  - Workflow
summary: Update tags of a workflow
description: Update tags of a workflow.
x-required-scope: workflowTags:update
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    name: workflowId
    in: path
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
          required:
            - id
          additionalProperties: false
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          $ref: ../../../../shared/spec/schemas/workflowTagsPublicDto.generated.yml
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
  '415':
    $ref: ../../../../shared/spec/responses/unsupportedMediaType.yml
