operationId: clearDataTableRows
tags:
  - DataTable
summary: Clear all rows from a data table
description: Permanently deletes all rows from a data table. The table structure will be retained. This action cannot be undone.
x-required-scope: dataTableRow:delete
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
      format: nanoid
      pattern: ^[A-Za-z0-9]{16}$
    required: true
    description: The ID of the data table
    name: dataTableId
    in: path
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            deletedCount:
              type: integer
              description: The number of rows that were deleted
          required:
            - deletedCount
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
