operationId: deleteDataTable
tags:
  - DataTable
summary: Delete a data table
description: Delete a data table. This will also delete all rows in the table.
x-required-scope: dataTable:delete
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
      format: nanoid
      pattern: ^[A-Za-z0-9]{16}$
    required: true
    description: The ID of the data table
    name: dataTableId
    in: path
responses:
  '204':
    description: Operation successful.
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
