operationId: updateDataTable
tags:
  - DataTable
summary: Update a data table
description: Update a data table's name.
x-required-scope: dataTable:update
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
      format: nanoid
      pattern: ^[A-Za-z0-9]{16}$
    required: true
    description: The ID of the data table
    name: dataTableId
    in: path
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          name:
            type: string
            minLength: 1
            maxLength: 128
            description: New name for the data table
            example: updated-customers
        required:
          - name
        additionalProperties: false
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          $ref: ../../../../shared/spec/schemas/dataTablePublicDto.generated.yml
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
  '409':
    $ref: ../../../../shared/spec/responses/conflict.yml
  '415':
    $ref: ../../../../shared/spec/responses/unsupportedMediaType.yml
