/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface UserListOrderedRequest {
    /**
     * Page number for pagination, starting from 1
     */
    pageNumber?: number;
    /**
     * Number of users to retrieve per page
     */
    pageSize?: number;
}
