/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 64eca0424b63
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest = {
  datasetId: string;
  patchDatasetInSchema: components.PatchDatasetInSchema;
};

/** @internal */
export type UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$Outbound =
  {
    dataset_id: string;
    PatchDatasetInSchema: components.PatchDatasetInSchema$Outbound;
  };

/** @internal */
export const UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$outboundSchema:
  z.ZodType<
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$Outbound,
    z.ZodTypeDef,
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest
  > = z.object({
    datasetId: z.string(),
    patchDatasetInSchema: components.PatchDatasetInSchema$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      patchDatasetInSchema: "PatchDatasetInSchema",
    });
  });

export function updateDatasetV1ObservabilityDatasetsDatasetIdPatchRequestToJSON(
  updateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest:
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest,
): string {
  return JSON.stringify(
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$outboundSchema
      .parse(updateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest),
  );
}
