"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClassificationTargetResult$ = exports.ClassificationTargetResult$outboundSchema = exports.ClassificationTargetResult$inboundSchema = void 0;
exports.classificationTargetResultToJSON = classificationTargetResultToJSON;
exports.classificationTargetResultFromJSON = classificationTargetResultFromJSON;
const z = __importStar(require("zod"));
const schemas_js_1 = require("../../lib/schemas.js");
/** @internal */
exports.ClassificationTargetResult$inboundSchema = z.object({
    scores: z.record(z.number()),
});
/** @internal */
exports.ClassificationTargetResult$outboundSchema = z.object({
    scores: z.record(z.number()),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var ClassificationTargetResult$;
(function (ClassificationTargetResult$) {
    /** @deprecated use `ClassificationTargetResult$inboundSchema` instead. */
    ClassificationTargetResult$.inboundSchema = exports.ClassificationTargetResult$inboundSchema;
    /** @deprecated use `ClassificationTargetResult$outboundSchema` instead. */
    ClassificationTargetResult$.outboundSchema = exports.ClassificationTargetResult$outboundSchema;
})(ClassificationTargetResult$ || (exports.ClassificationTargetResult$ = ClassificationTargetResult$ = {}));
function classificationTargetResultToJSON(classificationTargetResult) {
    return JSON.stringify(exports.ClassificationTargetResult$outboundSchema.parse(classificationTargetResult));
}
function classificationTargetResultFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.ClassificationTargetResult$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ClassificationTargetResult' from JSON`);
}
//# sourceMappingURL=classificationtargetresult.js.map