"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Audio = void 0;
const sdks_js_1 = require("../lib/sdks.js");
const transcriptions_js_1 = require("./transcriptions.js");
class Audio extends sdks_js_1.ClientSDK {
    get transcriptions() {
        return (this._transcriptions ?? (this._transcriptions = new transcriptions_js_1.Transcriptions(this._options)));
    }
}
exports.Audio = Audio;
//# sourceMappingURL=audio.js.map