"use strict";
/**
 * 1Password Connect
 * API interface for the 1Password Connect server.
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FullItemAllOfFields = void 0;
class FullItemAllOfFields {
    static getAttributeTypeMap() {
        return FullItemAllOfFields.attributeTypeMap;
    }
}
exports.FullItemAllOfFields = FullItemAllOfFields;
FullItemAllOfFields.discriminator = undefined;
FullItemAllOfFields.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "section",
        "baseName": "section",
        "type": "FullItemAllOfSection"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "FullItemAllOfFields.TypeEnum"
    },
    {
        "name": "purpose",
        "baseName": "purpose",
        "type": "FullItemAllOfFields.PurposeEnum"
    },
    {
        "name": "label",
        "baseName": "label",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "string"
    },
    {
        "name": "generate",
        "baseName": "generate",
        "type": "boolean"
    },
    {
        "name": "recipe",
        "baseName": "recipe",
        "type": "GeneratorRecipe"
    },
    {
        "name": "entropy",
        "baseName": "entropy",
        "type": "number"
    },
    {
        "name": "otp",
        "baseName": "totp",
        "type": "string"
    }
];
(function (FullItemAllOfFields) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["String"] = 'STRING'] = "String";
        TypeEnum[TypeEnum["Email"] = 'EMAIL'] = "Email";
        TypeEnum[TypeEnum["Concealed"] = 'CONCEALED'] = "Concealed";
        TypeEnum[TypeEnum["Url"] = 'URL'] = "Url";
        /** @deprecated use {@link TypeEnum.Otp} instead. */
        TypeEnum[TypeEnum["Totp"] = 'OTP'] = "Totp";
        TypeEnum[TypeEnum["Otp"] = 'OTP'] = "Otp";
        TypeEnum[TypeEnum["Date"] = 'DATE'] = "Date";
        TypeEnum[TypeEnum["MonthYear"] = 'MONTH_YEAR'] = "MonthYear";
        TypeEnum[TypeEnum["Menu"] = 'MENU'] = "Menu";
    })(TypeEnum = FullItemAllOfFields.TypeEnum || (FullItemAllOfFields.TypeEnum = {}));
    let PurposeEnum;
    (function (PurposeEnum) {
        PurposeEnum[PurposeEnum["Empty"] = ''] = "Empty";
        PurposeEnum[PurposeEnum["Username"] = 'USERNAME'] = "Username";
        PurposeEnum[PurposeEnum["Password"] = 'PASSWORD'] = "Password";
        PurposeEnum[PurposeEnum["Notes"] = 'NOTES'] = "Notes";
    })(PurposeEnum = FullItemAllOfFields.PurposeEnum || (FullItemAllOfFields.PurposeEnum = {}));
})(FullItemAllOfFields || (exports.FullItemAllOfFields = FullItemAllOfFields = {}));
//# sourceMappingURL=fullItemAllOfFields.js.map