/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a24a91eaef8
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteModelV1ModelsModelIdDeleteRequest = {
  /**
   * The ID of the model to delete.
   */
  modelId: string;
};

/** @internal */
export type DeleteModelV1ModelsModelIdDeleteRequest$Outbound = {
  model_id: string;
};

/** @internal */
export const DeleteModelV1ModelsModelIdDeleteRequest$outboundSchema: z.ZodType<
  DeleteModelV1ModelsModelIdDeleteRequest$Outbound,
  z.ZodTypeDef,
  DeleteModelV1ModelsModelIdDeleteRequest
> = z.object({
  modelId: z.string(),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
  });
});

export function deleteModelV1ModelsModelIdDeleteRequestToJSON(
  deleteModelV1ModelsModelIdDeleteRequest:
    DeleteModelV1ModelsModelIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteModelV1ModelsModelIdDeleteRequest$outboundSchema.parse(
      deleteModelV1ModelsModelIdDeleteRequest,
    ),
  );
}
