allOf:
  - $ref: './credential.yml'
  - type: object
    properties:
      projectId:
        type: string
        description: Project to create the credential in. Defaults to the user's personal project.
        example: VmwOO9HeTEj20kxM
