/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Cohere from "../index";
export declare type AssistantMessageContentItem = Cohere.AssistantMessageContentItem.Text;
export declare namespace AssistantMessageContentItem {
    interface Text extends Cohere.TextContent {
        type: "text";
    }
}
