operationId: createWidget
tags:
  - Widgets
summary: Create a widget
description: Create a new widget.
x-required-scope: tag:create
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          name:
            type: string
            minLength: 1
          description:
            type: string
        required:
          - name
responses:
  '201':
    description: Operation successful.
    content:
      application/json:
        schema:
          $ref: ../../../../shared/spec/schemas/widgetPublicDto.generated.yml
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
