operationId: listWidgets
tags:
  - Widgets
summary: Retrieve all widgets
description: Retrieve all widgets from your instance.
x-required-scope: tag:list
parameters:
  - $ref: ../../../../shared/spec/parameters/limit.yml
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                    nullable: true
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                required:
                  - id
                  - name
                  - description
                  - createdAt
                  - updatedAt
          required:
            - data
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
