/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Zep from "../../api/index";
import * as core from "../../core";
export declare const ApiError: core.serialization.ObjectSchema<serializers.ApiError.Raw, Zep.ApiError>;
export declare namespace ApiError {
    interface Raw {
        message?: string | null;
    }
}
