post:
  x-eov-operation-id: testCredential
  x-eov-operation-handler: v1/handlers/credentials/credentials.handler
  tags:
    - Credential
  summary: Test credential by ID
  description: Tests a credential by ID using the stored credential data.
  operationId: testCredential
  parameters:
    - name: id
      in: path
      description: The credential ID
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/credentialTestResponse.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
