operationId: getCredential
tags:
  - Credential
summary: Get credential by ID
description: Retrieves a credential by ID. Credential data (secrets) is not included.
x-required-scope: credential:read
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    name: credentialId
    in: path
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            type:
              type: string
            isManaged:
              type: boolean
            isGlobal:
              type: boolean
            isResolvable:
              type: boolean
            resolvableAllowFallback:
              type: boolean
            resolverId:
              type: string
              nullable: true
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
          required:
            - id
            - name
            - type
            - isManaged
            - isGlobal
            - isResolvable
            - resolvableAllowFallback
            - resolverId
            - createdAt
            - updatedAt
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
