operationId: testCredential
tags:
  - Credential
summary: Test credential by ID
description: Tests a credential by ID using the stored credential data.
x-required-scope: credential:read
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    description: The ID of the credential.
    name: credentialId
    in: path
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: string
              enum:
                - OK
                - Error
              example: OK
            message:
              type: string
              example: Connection successful!
          required:
            - status
            - message
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
