operationId: transferCredential
tags:
  - Credential
summary: Transfer a credential to another project.
description: Transfer a credential to another project.
x-required-scope: credential:move
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    description: The ID of the credential.
    name: credentialId
    in: path
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          destinationProjectId:
            type: string
            description: The ID of the project to transfer the credential to.
            example: VmwOO9HeTEj20kxM
        required:
          - destinationProjectId
responses:
  '204':
    description: Operation successful.
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
  '415':
    $ref: ../../../../shared/spec/responses/unsupportedMediaType.yml
