export type GatewayEmbeddingModelId =
  | 'alibaba/qwen3-embedding-0.6b'
  | 'alibaba/qwen3-embedding-4b'
  | 'alibaba/qwen3-embedding-8b'
  | 'amazon/titan-embed-text-v2'
  | 'cohere/embed-v4.0'
  | 'google/gemini-embedding-001'
  | 'google/gemini-embedding-2'
  | 'google/text-embedding-005'
  | 'google/text-multilingual-embedding-002'
  | 'mistral/codestral-embed'
  | 'mistral/mistral-embed'
  | 'openai/text-embedding-3-large'
  | 'openai/text-embedding-3-small'
  | 'openai/text-embedding-ada-002'
  | 'voyage/voyage-3-large'
  | 'voyage/voyage-3.5'
  | 'voyage/voyage-3.5-lite'
  | 'voyage/voyage-4'
  | 'voyage/voyage-4-large'
  | 'voyage/voyage-4-lite'
  | 'voyage/voyage-code-2'
  | 'voyage/voyage-code-3'
  | 'voyage/voyage-finance-2'
  | 'voyage/voyage-law-2'
  | (string & {});
