type: object
additionalProperties: false
required:
  - workflowIds
properties:
  workflowIds:
    type: array
    minItems: 1
    maxItems: 300
    description: IDs of the workflows to include in the exported package.
    items:
      type: string
      minLength: 1
    example:
      - 2tUt1wbLX592XDdX
