/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f7b221b25c51
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BaseTaskStatus,
  BaseTaskStatus$inboundSchema,
} from "./basetaskstatus.js";

export type CampaignStatus = {
  status: BaseTaskStatus;
};

/** @internal */
export const CampaignStatus$inboundSchema: z.ZodType<
  CampaignStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: BaseTaskStatus$inboundSchema,
});

export function campaignStatusFromJSON(
  jsonString: string,
): SafeParseResult<CampaignStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CampaignStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CampaignStatus' from JSON`,
  );
}
