operationId: getVariables
tags:
  - Variables
summary: Retrieve variables
description: Retrieve variables from your instance.
x-required-scope: variable:list
parameters:
  - $ref: ../../../../shared/spec/parameters/limit.yml
  - $ref: ../../../../shared/spec/parameters/cursor.yml
  - schema:
      type: string
      example: VmwOO9HeTEj20kxM
    required: false
    name: projectId
    in: query
  - schema:
      type: string
      enum:
        - empty
    required: false
    name: state
    in: query
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    readOnly: true
                  key:
                    type: string
                  value:
                    type: string
                    example: test
                  type:
                    type: string
                    readOnly: true
                  project:
                    type: object
                    nullable: true
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      type:
                        type: string
                        enum:
                          - personal
                          - team
                      icon:
                        type: object
                        nullable: true
                        properties:
                          type:
                            type: string
                            enum:
                              - emoji
                              - icon
                          value:
                            type: string
                        required:
                          - type
                          - value
                      description:
                        type: string
                        nullable: true
                      customTelemetryTags:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            value:
                              type: string
                          required:
                            - key
                            - value
                      creatorId:
                        type: string
                        nullable: true
                      createdAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type: string
                        format: date-time
                    required:
                      - id
                      - name
                      - type
                      - icon
                      - description
                      - customTelemetryTags
                      - creatorId
                      - createdAt
                      - updatedAt
                required:
                  - id
                  - key
                  - value
                  - type
                  - project
            nextCursor:
              type: string
              nullable: true
          required:
            - data
            - nextCursor
  '400':
    $ref: ../../../../shared/spec/responses/badRequest.yml
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
