post:
  x-eov-operation-id: createVariable
  x-required-scope: variable:create
  x-eov-operation-handler: v1/handlers/variables/variables.handler
  tags:
    - Variables
  summary: Create a variable
  description: Create a variable in your instance.
  requestBody:
    description: Payload for variable to create.
    content:
      application/json:
        schema:
          $ref: '../schemas/variable.create.yml'
    required: true
  responses:
    '201':
      description: Operation successful.
    '400':
      $ref: '../../../../shared/spec/responses/badRequest.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
