operationId: getPolicyDocument
tags:
  - NodeTypePolicy
summary: Retrieve a node type policy document
x-required-scope: nodeTypePolicy:manage
x-eov-operation-id: unreachable
x-eov-operation-handler: v1/handlers/decorator-routed.handler
x-decorator-routed: true
parameters:
  - schema:
      type: string
    required: true
    description: The ID of the node type policy document.
    name: policyId
    in: path
responses:
  '200':
    description: Operation successful.
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: string
            kind:
              type: string
            rules:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                  action:
                    type: string
                    enum:
                      - allow
                      - deny
                      - delegate
                  selector:
                    oneOf:
                      - type: object
                        properties:
                          kind:
                            type: string
                            enum:
                              - name
                          value:
                            type: string
                            minLength: 1
                        required:
                          - kind
                          - value
                      - type: object
                        properties:
                          kind:
                            type: string
                            enum:
                              - package
                          value:
                            type: string
                            minLength: 1
                        required:
                          - kind
                          - value
                required:
                  - id
                  - action
                  - selector
            version:
              type: integer
              minimum: 0
              exclusiveMinimum: true
            updatedBy:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
          required:
            - id
            - kind
            - rules
            - version
            - updatedBy
            - createdAt
            - updatedAt
  '401':
    $ref: ../../../../shared/spec/responses/unauthorized.yml
  '403':
    $ref: ../../../../shared/spec/responses/forbidden.yml
  '404':
    $ref: ../../../../shared/spec/responses/notFound.yml
  '503':
    $ref: ../../../../shared/spec/responses/serviceUnavailable.yml
