"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 761cefb4bff3
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ObservabilityErrorCode$inboundSchema = exports.ObservabilityErrorCode = void 0;
const z = __importStar(require("zod/v3"));
exports.ObservabilityErrorCode = {
    UnknownError: "UNKNOWN_ERROR",
    ValidationError: "VALIDATION_ERROR",
    AuthForbidden: "AUTH_FORBIDDEN",
    AuthForbiddenNotWorkspaceAdmin: "AUTH_FORBIDDEN_NOT_WORKSPACE_ADMIN",
    AuthForbiddenWorkspaceNotFound: "AUTH_FORBIDDEN_WORKSPACE_NOT_FOUND",
    AuthForbiddenRoleNotFound: "AUTH_FORBIDDEN_ROLE_NOT_FOUND",
    AuthForbiddenOrgNotWhitelisted: "AUTH_FORBIDDEN_ORG_NOT_WHITELISTED",
    AuthUnauthorized: "AUTH_UNAUTHORIZED",
    FeatureNotSupported: "FEATURE_NOT_SUPPORTED",
    FieldsBadRequest: "FIELDS_BAD_REQUEST",
    FieldsNotFound: "FIELDS_NOT_FOUND",
    SearchNotFound: "SEARCH_NOT_FOUND",
    SearchBadRequest: "SEARCH_BAD_REQUEST",
    SearchServiceUnavailable: "SEARCH_SERVICE_UNAVAILABLE",
    DatabaseError: "DATABASE_ERROR",
    DatabaseTimeout: "DATABASE_TIMEOUT",
    DatabaseUnavailable: "DATABASE_UNAVAILABLE",
    DatabaseQueryError: "DATABASE_QUERY_ERROR",
    SearchFilterToSqlConversionError: "SEARCH_FILTER_TO_SQL_CONVERSION_ERROR",
    JudgeConversationFormatError: "JUDGE_CONVERSATION_FORMAT_ERROR",
    JudgeMistralApiError: "JUDGE_MISTRAL_API_ERROR",
    JudgeMistralApiTimeout: "JUDGE_MISTRAL_API_TIMEOUT",
    JudgeNameAlreadyExists: "JUDGE_NAME_ALREADY_EXISTS",
    JudgeNotFound: "JUDGE_NOT_FOUND",
    JudgeAlreadyHasNewVersion: "JUDGE_ALREADY_HAS_NEW_VERSION",
    JudgeUsedInCampaignCannotBeUpdated: "JUDGE_USED_IN_CAMPAIGN_CANNOT_BE_UPDATED",
    JudgeDidNotChange: "JUDGE_DID_NOT_CHANGE",
    CampaignNotFound: "CAMPAIGN_NOT_FOUND",
    CampaignNoMatchingEvents: "CAMPAIGN_NO_MATCHING_EVENTS",
    DatasetNotFound: "DATASET_NOT_FOUND",
    DatasetTaskNotFound: "DATASET_TASK_NOT_FOUND",
    DatasetRecordNotFound: "DATASET_RECORD_NOT_FOUND",
    DatasetRecordFormatError: "DATASET_RECORD_FORMAT_ERROR",
    AgentNotFound: "AGENT_NOT_FOUND",
    AgentMistralApiError: "AGENT_MISTRAL_API_ERROR",
    EvaluationNotFound: "EVALUATION_NOT_FOUND",
    EvaluationCurrentlyRunning: "EVALUATION_CURRENTLY_RUNNING",
    EvaluationRecordNotFound: "EVALUATION_RECORD_NOT_FOUND",
    EvaluationRunNotFound: "EVALUATION_RUN_NOT_FOUND",
    EvaluationRunTransitionIsInvalid: "EVALUATION_RUN_TRANSITION_IS_INVALID",
    EvaluationRunTransitionIsRunningAlready: "EVALUATION_RUN_TRANSITION_IS_RUNNING_ALREADY",
    EvaluationRunTransitionError: "EVALUATION_RUN_TRANSITION_ERROR",
    TemplateSyntaxError: "TEMPLATE_SYNTAX_ERROR",
};
/** @internal */
exports.ObservabilityErrorCode$inboundSchema = z.nativeEnum(exports.ObservabilityErrorCode);
//# sourceMappingURL=observabilityerrorcode.js.map