/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ReferenceChunk,
  ReferenceChunk$Outbound,
  ReferenceChunk$outboundSchema,
} from "./referencechunk.js";
import {
  TextChunk,
  TextChunk$Outbound,
  TextChunk$outboundSchema,
} from "./textchunk.js";
import {
  ToolReferenceChunk,
  ToolReferenceChunk$Outbound,
  ToolReferenceChunk$outboundSchema,
} from "./toolreferencechunk.js";

export type Thinking = ToolReferenceChunk | TextChunk | ReferenceChunk;

export type ThinkChunk = {
  type?: "thinking" | undefined;
  thinking: Array<ToolReferenceChunk | TextChunk | ReferenceChunk>;
  /**
   * Whether the thinking chunk is closed or not. Currently only used for prefixing.
   */
  closed?: boolean | undefined;
};

/** @internal */
export type Thinking$Outbound =
  | ToolReferenceChunk$Outbound
  | TextChunk$Outbound
  | ReferenceChunk$Outbound;

/** @internal */
export const Thinking$outboundSchema: z.ZodType<
  Thinking$Outbound,
  z.ZodTypeDef,
  Thinking
> = z.union([
  ToolReferenceChunk$outboundSchema,
  TextChunk$outboundSchema,
  ReferenceChunk$outboundSchema,
]);

export function thinkingToJSON(thinking: Thinking): string {
  return JSON.stringify(Thinking$outboundSchema.parse(thinking));
}

/** @internal */
export type ThinkChunk$Outbound = {
  type: "thinking";
  thinking: Array<
    ToolReferenceChunk$Outbound | TextChunk$Outbound | ReferenceChunk$Outbound
  >;
  closed?: boolean | undefined;
};

/** @internal */
export const ThinkChunk$outboundSchema: z.ZodType<
  ThinkChunk$Outbound,
  z.ZodTypeDef,
  ThinkChunk
> = z.object({
  type: z.literal("thinking").default("thinking" as const),
  thinking: z.array(
    z.union([
      ToolReferenceChunk$outboundSchema,
      TextChunk$outboundSchema,
      ReferenceChunk$outboundSchema,
    ]),
  ),
  closed: z.boolean().optional(),
});

export function thinkChunkToJSON(thinkChunk: ThinkChunk): string {
  return JSON.stringify(ThinkChunk$outboundSchema.parse(thinkChunk));
}
