"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.LibrariesDocumentsGetSignedUrlV1Request$ = exports.LibrariesDocumentsGetSignedUrlV1Request$outboundSchema = exports.LibrariesDocumentsGetSignedUrlV1Request$inboundSchema = void 0;
exports.librariesDocumentsGetSignedUrlV1RequestToJSON = librariesDocumentsGetSignedUrlV1RequestToJSON;
exports.librariesDocumentsGetSignedUrlV1RequestFromJSON = librariesDocumentsGetSignedUrlV1RequestFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
/** @internal */
exports.LibrariesDocumentsGetSignedUrlV1Request$inboundSchema = z.object({
    library_id: z.string(),
    document_id: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "library_id": "libraryId",
        "document_id": "documentId",
    });
});
/** @internal */
exports.LibrariesDocumentsGetSignedUrlV1Request$outboundSchema = z.object({
    libraryId: z.string(),
    documentId: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        libraryId: "library_id",
        documentId: "document_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var LibrariesDocumentsGetSignedUrlV1Request$;
(function (LibrariesDocumentsGetSignedUrlV1Request$) {
    /** @deprecated use `LibrariesDocumentsGetSignedUrlV1Request$inboundSchema` instead. */
    LibrariesDocumentsGetSignedUrlV1Request$.inboundSchema = exports.LibrariesDocumentsGetSignedUrlV1Request$inboundSchema;
    /** @deprecated use `LibrariesDocumentsGetSignedUrlV1Request$outboundSchema` instead. */
    LibrariesDocumentsGetSignedUrlV1Request$.outboundSchema = exports.LibrariesDocumentsGetSignedUrlV1Request$outboundSchema;
})(LibrariesDocumentsGetSignedUrlV1Request$ || (exports.LibrariesDocumentsGetSignedUrlV1Request$ = LibrariesDocumentsGetSignedUrlV1Request$ = {}));
function librariesDocumentsGetSignedUrlV1RequestToJSON(librariesDocumentsGetSignedUrlV1Request) {
    return JSON.stringify(exports.LibrariesDocumentsGetSignedUrlV1Request$outboundSchema.parse(librariesDocumentsGetSignedUrlV1Request));
}
function librariesDocumentsGetSignedUrlV1RequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.LibrariesDocumentsGetSignedUrlV1Request$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'LibrariesDocumentsGetSignedUrlV1Request' from JSON`);
}
//# sourceMappingURL=librariesdocumentsgetsignedurlv1.js.map