openapi: 3.0.0
info:
  title: decorator-routes
  version: 0.0.0
paths:
  /tags:
    get:
      $ref: ./handlers/tags/spec/paths/getTags.generated.yml
  /workflows/{workflowId}:
    get:
      $ref: ./handlers/workflows/spec/paths/getWorkflow.generated.yml
  /workflows/{workflowId}/archive:
    post:
      $ref: ./handlers/workflows/spec/paths/archiveWorkflow.generated.yml
  /workflows/{workflowId}/unarchive:
    post:
      $ref: ./handlers/workflows/spec/paths/unarchiveWorkflow.generated.yml
  /workflows/{workflowId}/transfer:
    put:
      $ref: ./handlers/workflows/spec/paths/transferWorkflow.generated.yml
  /workflows/{workflowId}/history:
    get:
      $ref: ./handlers/workflows/spec/paths/getWorkflowHistory.generated.yml
