//#region src/load/import_constants.ts
/** Auto-generated by import-constants plugin. Do not edit manually */
const optionalImportEntrypoints = [];
//#endregion
exports.optionalImportEntrypoints = optionalImportEntrypoints;

//# sourceMappingURL=import_constants.cjs.map