"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.LibraryIn$ = exports.LibraryIn$outboundSchema = exports.LibraryIn$inboundSchema = void 0;
exports.libraryInToJSON = libraryInToJSON;
exports.libraryInFromJSON = libraryInFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
/** @internal */
exports.LibraryIn$inboundSchema = z.object({
    name: z.string(),
    description: z.nullable(z.string()).optional(),
    chunk_size: z.nullable(z.number().int()).optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "chunk_size": "chunkSize",
    });
});
/** @internal */
exports.LibraryIn$outboundSchema = z.object({
    name: z.string(),
    description: z.nullable(z.string()).optional(),
    chunkSize: z.nullable(z.number().int()).optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        chunkSize: "chunk_size",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var LibraryIn$;
(function (LibraryIn$) {
    /** @deprecated use `LibraryIn$inboundSchema` instead. */
    LibraryIn$.inboundSchema = exports.LibraryIn$inboundSchema;
    /** @deprecated use `LibraryIn$outboundSchema` instead. */
    LibraryIn$.outboundSchema = exports.LibraryIn$outboundSchema;
})(LibraryIn$ || (exports.LibraryIn$ = LibraryIn$ = {}));
function libraryInToJSON(libraryIn) {
    return JSON.stringify(exports.LibraryIn$outboundSchema.parse(libraryIn));
}
function libraryInFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.LibraryIn$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'LibraryIn' from JSON`);
}
//# sourceMappingURL=libraryin.js.map