/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Zep from "../index";
export interface MemorySearchResult {
    message?: Zep.Message;
    metadata?: Record<string, unknown>;
    score?: number;
    summary?: Zep.Summary;
}
