name: 'CI: Check PR Title'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - 'master'
      - '1.x'

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Validate PR title
        uses: n8n-io/validate-n8n-pull-request-title@8aad0456a34b6f487c421539210529304ae8042c # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
