name: 'CI: Check Do Not Merge'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - 'master'
      - '1.x'

jobs:
  check-do-not-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Fail if 'Do Not Merge' label is present
        if: contains(github.event.pull_request.labels.*.name, 'Do Not Merge')
        run: |
          echo "::error::This PR has the 'Do Not Merge' label and cannot be merged."
          exit 1
