name: 'Release: Schedule Patch Release PRs'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 3-5,1' # 9am CET (UTC+1), Wednesday - Friday and Monday. (Minor release on tuesday)

jobs:
  create-patch-prs:
    name: Create patch release PR (${{ matrix.track }})
    strategy:
      matrix:
        track: [stable, beta, v1]
    uses: ./.github/workflows/release-create-patch-pr.yml
    secrets: inherit
    with:
      track: ${{ matrix.track }}
