name: 'Release: Schedule Patch Release PRs'

on:
  schedule:
    - cron: '0 8 * * 2-5' # 9am CET (UTC+1), Tuesday–Friday

jobs:
  create-patch-prs:
    name: Create patch release PR (${{ matrix.track }})
    strategy:
      matrix:
        track: [stable, beta, v1]
    uses: ./.github/workflows/release-create-patch-pr.yml
    secrets: inherit
    with:
      track: ${{ matrix.track }}
