name: 'Sec: Zizmor Scan'

on:
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:
  zizmor_scan:
    name: Zizmor Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: useblacksmith/checkout@bcec731f1eb1367240608d1c889a75b96db6ec53 # v1.5.0

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
