name: 'Test: Workflow scripts'

on:
  workflow_call:
    inputs:
      ref:
        description: GitHub ref to lint.
        required: false
        type: string
        default: ''
      nodeVersion:
        description: Version of node to use.
        required: false
        type: string
        default: 26.5.1

env:
  NODE_OPTIONS: --max-old-space-size=7168

jobs:
  workflow-script-tests:
    name: Run tests for workflow scripts
    runs-on: ${{ vars.RUNNER_PROVIDER == 'github' && 'ubuntu-slim' || 'blacksmith-4vcpu-ubuntu-2204' }}
    steps:
      - uses: useblacksmith/checkout@bcec731f1eb1367240608d1c889a75b96db6ec53 # v1.5.0
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs
        with:
          build-command: ''
          install-command: pnpm install --frozen-lockfile --dir ./.github/scripts --ignore-workspace
          cache-dependency-path: .github/scripts/pnpm-lock.yaml

      - name: Run tests
        id: run-tests
        run: npm test --prefix=.github/scripts

      - name: Check cubic.yaml
        if: ${{ !cancelled() }}
        run: node .github/scripts/quality/check-cubic-config.mjs
