name: 'Update pointer tags'

on:
  workflow_call:

jobs:
  update-pointer-tags:
    name: Update pointer tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
