name: 'Util: Ensure release candidate branches'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  ensure-release-candidate-branches:
    name: Ensure release-candidate branches
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs
        with:
          install-command: npm install --prefix=.github/scripts --no-package-lock
          build-command: ''

      - name: Ensure release-candidate branches
        run: node ./.github/scripts/ensure-release-candidate-branches.mjs
