name: Build n8n

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.22.0 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

version: "3"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    restart: always
