"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$ = exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$outboundSchema = exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$inboundSchema = exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$ = exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$outboundSchema = exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$inboundSchema = void 0;
exports.jobsApiRoutesFineTuningCancelFineTuningJobRequestToJSON = jobsApiRoutesFineTuningCancelFineTuningJobRequestToJSON;
exports.jobsApiRoutesFineTuningCancelFineTuningJobRequestFromJSON = jobsApiRoutesFineTuningCancelFineTuningJobRequestFromJSON;
exports.jobsApiRoutesFineTuningCancelFineTuningJobResponseToJSON = jobsApiRoutesFineTuningCancelFineTuningJobResponseToJSON;
exports.jobsApiRoutesFineTuningCancelFineTuningJobResponseFromJSON = jobsApiRoutesFineTuningCancelFineTuningJobResponseFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const components = __importStar(require("../components/index.js"));
/** @internal */
exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$inboundSchema = z.object({
    job_id: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "job_id": "jobId",
    });
});
/** @internal */
exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$outboundSchema = z.object({
    jobId: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        jobId: "job_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var JobsApiRoutesFineTuningCancelFineTuningJobRequest$;
(function (JobsApiRoutesFineTuningCancelFineTuningJobRequest$) {
    /** @deprecated use `JobsApiRoutesFineTuningCancelFineTuningJobRequest$inboundSchema` instead. */
    JobsApiRoutesFineTuningCancelFineTuningJobRequest$.inboundSchema = exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$inboundSchema;
    /** @deprecated use `JobsApiRoutesFineTuningCancelFineTuningJobRequest$outboundSchema` instead. */
    JobsApiRoutesFineTuningCancelFineTuningJobRequest$.outboundSchema = exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$outboundSchema;
})(JobsApiRoutesFineTuningCancelFineTuningJobRequest$ || (exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$ = JobsApiRoutesFineTuningCancelFineTuningJobRequest$ = {}));
function jobsApiRoutesFineTuningCancelFineTuningJobRequestToJSON(jobsApiRoutesFineTuningCancelFineTuningJobRequest) {
    return JSON.stringify(exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$outboundSchema.parse(jobsApiRoutesFineTuningCancelFineTuningJobRequest));
}
function jobsApiRoutesFineTuningCancelFineTuningJobRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.JobsApiRoutesFineTuningCancelFineTuningJobRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'JobsApiRoutesFineTuningCancelFineTuningJobRequest' from JSON`);
}
/** @internal */
exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$inboundSchema = z.union([
    components.ClassifierDetailedJobOut$inboundSchema.and(z.object({ job_type: z.literal("classifier") }).transform((v) => ({
        jobType: v.job_type,
    }))),
    components.CompletionDetailedJobOut$inboundSchema.and(z.object({ job_type: z.literal("completion") }).transform((v) => ({
        jobType: v.job_type,
    }))),
]);
/** @internal */
exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$outboundSchema = z.union([
    components.ClassifierDetailedJobOut$outboundSchema.and(z.object({ jobType: z.literal("classifier") }).transform((v) => ({
        job_type: v.jobType,
    }))),
    components.CompletionDetailedJobOut$outboundSchema.and(z.object({ jobType: z.literal("completion") }).transform((v) => ({
        job_type: v.jobType,
    }))),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var JobsApiRoutesFineTuningCancelFineTuningJobResponse$;
(function (JobsApiRoutesFineTuningCancelFineTuningJobResponse$) {
    /** @deprecated use `JobsApiRoutesFineTuningCancelFineTuningJobResponse$inboundSchema` instead. */
    JobsApiRoutesFineTuningCancelFineTuningJobResponse$.inboundSchema = exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$inboundSchema;
    /** @deprecated use `JobsApiRoutesFineTuningCancelFineTuningJobResponse$outboundSchema` instead. */
    JobsApiRoutesFineTuningCancelFineTuningJobResponse$.outboundSchema = exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$outboundSchema;
})(JobsApiRoutesFineTuningCancelFineTuningJobResponse$ || (exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$ = JobsApiRoutesFineTuningCancelFineTuningJobResponse$ = {}));
function jobsApiRoutesFineTuningCancelFineTuningJobResponseToJSON(jobsApiRoutesFineTuningCancelFineTuningJobResponse) {
    return JSON.stringify(exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$outboundSchema.parse(jobsApiRoutesFineTuningCancelFineTuningJobResponse));
}
function jobsApiRoutesFineTuningCancelFineTuningJobResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.JobsApiRoutesFineTuningCancelFineTuningJobResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'JobsApiRoutesFineTuningCancelFineTuningJobResponse' from JSON`);
}
//# sourceMappingURL=jobsapiroutesfinetuningcancelfinetuningjob.js.map